[project]
name = "SkyDock"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.badges]
path = "contracts/badges.clar"
depends_on = []

[contracts.rewards]
path = "contracts/rewards.clar"
depends_on = []

[contracts.vault]
path = "contracts/vault.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
